update gitlab-ci

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -124,9 +124,18 @@ Push Version:
       JSON_PAYLOAD="{ \"app\": \"$CI_PROJECT_NAME\", \"version\": \"$IMAGE_TAG\", \"build_number\": $CI_PIPELINE_ID, \"notes\": \"$NOTES\" }"
 
       # Pass the payload to curl
-      curl --request POST https://license.finmars.com/api/v1/version/ \
+      response=$(curl --request POST https://license.finmars.com/api/v1/version/ \
       --header "Content-Type: application/json" \
-      --data "$JSON_PAYLOAD"
+      --data "$JSON_PAYLOAD")
+      
+      if [[ "$response" -ne 200 ]]; then
+        echo "Error detected. Failing the build."
+        exit 1
+      else
+        echo "Build succeeded."
+      fi
+      
+
   only:
     - /^.*-rc$/
     - tags
